config/routes.rb
Rails.application.routes.draw do
  resources :exercise_galleries
  resources :workout_infos
  devise_for :users
  root 'home#page'
  resources :exercise_infos
  resources :user_infos
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

# <% @difficulty = ["beginner", "intermediate", "advanced"]%>
# <% @types_of_workouts = ["strength or resistance training", "cardio", "HIIT", "other..."]%>

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def page
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/page.html.erb
<div class="jumbotron">
  <div class="row">
    <div class="col-md-12 ">
      <h1>Welcome to the Workout Creator</h1>
      <h6 class="sub-heading">Fill your exercise gallery and use them to create and collect customized workouts</h6>
      <div class="btn-div">
        <button type="button" class="home-btns"><%= link_to "Add to exercise gallery", new_exercise_gallery_path %></button>
        <button type="button" class="home-btns"><%= link_to "View exercise gallery", exercise_galleries_path %></button>
        <button type="button" class="home-btns"><%= link_to "Create A New Workout", new_workout_info_path %></button>
        <button type="button" class="home-btns"><%= link_to 'View Existing Workouts', workout_infos_path %></button>
        <button type="button" class="home-btns"><%= link_to 'View/Edit Profile', user_infos_path %></button>
        
      </div>
    </div>
  </div>
</div>