config/routes.rb
Rails.application.routes.draw do
  resources :exercise_galleries
  resources :workout_infos
  devise_for :users
  root 'home#page'
  resources :exercise_infos
  resources :user_infos
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

# <% @difficulty = ["beginner", "intermediate", "advanced"]%>
# <% @types_of_workouts = ["strength or resistance training", "cardio", "HIIT", "other..."]%>

app/models/exercise_info.rb
class ExerciseInfo < ApplicationRecord
  belongs_to :user
  belongs_to :workout_info
end

app/controllers/exercise_infos_controller.rb
class ExerciseInfosController < ApplicationController
  before_action :set_exercise_info, only: [:show, :edit, :update, :destroy]
  # before_action :set_workout_info

  # GET /exercise_infos
  # GET /exercise_infos.json
  def index
    @exercise_infos = ExerciseInfo.all
  end

  # GET /exercise_infos/1
  # GET /exercise_infos/1.json
  def show
  end

  # GET /exercise_infos/new
  def new
    @exercises = ExerciseGallery.all
    # @exercises = @exercises.map{|e| e.name}
    @exercise_info = ExerciseInfo.new

  end

  # GET /exercise_infos/1/edit
  def edit
  end

  # POST /exercise_infos
  # POST /exercise_infos.json
  def create
    @exercise_info = ExerciseInfo.new(exercise_info_params)

    respond_to do |format|
      if @exercise_info.save
        format.html { redirect_to @exercise_info, notice: 'Exercise info was successfully created.' }
        format.json { render :show, status: :created, location: @exercise_info }
      else
        format.html { render :new }
        format.json { render json: @exercise_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exercise_infos/1
  # PATCH/PUT /exercise_infos/1.json
  def update
    respond_to do |format|
      if @exercise_info.update(exercise_info_params)
        format.html { redirect_to @exercise_info, notice: 'Exercise info was successfully updated.' }
        format.json { render :show, status: :ok, location: @exercise_info }
      else
        format.html { render :edit }
        format.json { render json: @exercise_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exercise_infos/1
  # DELETE /exercise_infos/1.json
  def destroy
    @exercise_info.destroy
    respond_to do |format|
      format.html { redirect_to exercise_infos_url, notice: 'Exercise info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exercise_info
      @exercise_info = ExerciseInfo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def exercise_info_params
      params.require(:exercise_info).permit(:name, :reps, :time, :sets, :weight_needed, :equipment_needed, :user_id, :workout_info_id)
    end

    # def set_workout_info
    #   @workout_info_id = WorkoutInfo.find(params[:id])
    # end
end


# figure out how to link workout id

app/helpers/exercise_infos_helper.rb
module ExerciseInfosHelper
end

app/views/exercise_infos/_form.html.erb
<%= simple_form_for(@exercise_info) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  

  
<% end %>



<%= form_with model: @exercise_info do |f| %>
  <div class="form-inputs">
    <div>
    <%= f.label :use_existing_exercise %>
    <%= f.collection_select :name, @exercises, :id, :name %>
    <p>Or add custom exercise</p>
    <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
    </div>
    <div>
    <%= f.label :reps %>
    <%= f.number_field :reps %>
    </div>
    <div>
    <%= f.label :time %>
    <%= f.number_field :time %>
    </div>
    <div>
    <%= f.label :sets %>
    <%= f.number_field :sets %>
    </div>
    <div>
    <%= f.label :weight_needed %>
    <%= f.number_field :weight_needed %>
    </div>
    <div>
    <%= f.label :equipment_needed %>
    <%= f.text_field :equipment_needed %>
    </div>
    <%#= f.association :workout_info %>
    <div class="form-actions">
    <%= f.button :submit %>
    </div>
  </div>
<% end %>

app/views/exercise_infos/edit.html.erb
<h1>Editing Exercise Info</h1>

<%= render 'form', exercise_info: @exercise_info %>

<%= link_to 'Show', @exercise_info %> |
<%= link_to 'Back', exercise_infos_path %>

app/views/exercise_infos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Exercises</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Reps</th>
      <th>Time</th>
      <th>Sets</th>
      <th>Weight needed</th>
      <th>Equipment needed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exercise_infos.each do |exercise_info| %>
      <tr>
        <td><%= exercise_info.name %></td>
        <td><%= exercise_info.reps %></td>
        <td><%= exercise_info.time %></td>
        <td><%= exercise_info.sets %></td>
        <td><%= exercise_info.weight_needed %></td>
        <td><%= exercise_info.equipment_needed %></td>
        <td><%= link_to 'Show', exercise_info %></td>
        <td><%= link_to 'Edit', edit_exercise_info_path(exercise_info) %></td>
        <td><%= link_to 'Destroy', exercise_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add new exercise', new_exercise_info_path %>

app/views/exercise_infos/new.html.erb
<h1>New Exercise </h1>

<%= render 'form', exercise_info: @exercise_info %>

<%= link_to 'Back', exercise_infos_path %>

app/views/exercise_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @exercise_info.name %>
</p>

<p>
  <strong>Reps:</strong>
  <%= @exercise_info.reps %>
</p>

<p>
  <strong>Time:</strong>
  <%= @exercise_info.time %>
</p>

<p>
  <strong>Sets:</strong>
  <%= @exercise_info.sets %>
</p>

<p>
  <strong>Weight needed:</strong>
  <%= @exercise_info.weight_needed %>
</p>

<p>
  <strong>Equipment needed:</strong>
  <%= @exercise_info.equipment_needed %>
</p>

<p>
  <strong>User:</strong>
  <%= @exercise_info.user_id %>
</p>

<p>
  <strong>Workout info:</strong>
  <%= @exercise_info.workout_info_id %>
</p>

<%= link_to 'Edit', edit_exercise_info_path(@exercise_info) %> |
<%= link_to 'Back', exercise_infos_path %>