config/routes.rb
Rails.application.routes.draw do
  resources :exercise_galleries
  resources :workout_infos
  devise_for :users
  root 'home#page'
  resources :exercise_infos
  resources :user_infos
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

# <% @difficulty = ["beginner", "intermediate", "advanced"]%>
# <% @types_of_workouts = ["strength or resistance training", "cardio", "HIIT", "other..."]%>

app/models/workout_info.rb
class WorkoutInfo < ApplicationRecord
  belongs_to :user
  validates :name, :difficulty, :muscle_groups, :workout_type, :user_id, presence: true
  has_one :exercise_info
end

app/controllers/workout_infos_controller.rb
class WorkoutInfosController < ApplicationController
  before_action :set_workout_info, only: [:show, :edit, :update, :destroy]
  before_action :set_dropdowns, only: [:new, :edit]

  # GET /workout_infos
  # GET /workout_infos.json
  def index
    @workout_infos = WorkoutInfo.all
    
  end

  # GET /workout_infos/1
  # GET /workout_infos/1.json
  def show
  end

  # GET /workout_infos/new
  def new
    # @difficulty = ["beginner", "intermediate", "advanced", "other"]
    # @workout_categories = ["strength or resistance training", "cardio", "HIIT", "other"]
    # @muscle_groups = ["full body", "legs", "core", "arms", "back"]
    @workout_info = WorkoutInfo.new
    @exericse 
  end

  # GET /workout_infos/1/edit
  def edit
    
  end

  # POST /workout_infos
  # POST /workout_infos.json
  def create
    @workout_info = WorkoutInfo.new(workout_info_params)

    @workout_info.user_id = current_user.id
    respond_to do |format|
      if @workout_info.save
        format.html { redirect_to @workout_info, notice: 'Workout info was successfully created.' }
        format.json { render :show, status: :created, location: @workout_info }
      else
        format.html { render :new }
        format.json { render json: @workout_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workout_infos/1
  # PATCH/PUT /workout_infos/1.json
  def update
    respond_to do |format|
      if @workout_info.update(workout_info_params)
        format.html { redirect_to @workout_info, notice: 'Workout info was successfully updated.' }
        format.json { render :show, status: :ok, location: @workout_info }
      else
        format.html { render :edit }
        format.json { render json: @workout_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workout_infos/1
  # DELETE /workout_infos/1.json
  def destroy
    @workout_info.destroy
    respond_to do |format|
      format.html { redirect_to workout_infos_url, notice: 'Workout info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workout_info
      @workout_info = WorkoutInfo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def workout_info_params
      params.require(:workout_info).permit(:name, :difficulty, :muscle_groups, :workout_type, :user_id)
    end
    
    # set options for drop down menus when creating new workout
    def set_dropdowns
      @difficulty = ["beginner", "intermediate", "advanced", "other"]
      @workout_categories = ["strength or resistance training", "cardio", "HIIT", "other"]
      @muscle_groups = ["full body", "legs", "core", "arms", "back"]
    end
end

app/helpers/workout_infos_helper.rb
module WorkoutInfosHelper
end

app/views/workout_infos/_form.html.erb
  <%#= f.error_notification %>
  <%#= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

<div class="form-inputs-workout">
  <%= form_with model: @workout_info do |form| %>
  
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name%>
  </div>
  <div class="field">
    <%= form.label :difficulty %>
    <%= form.select :difficulty, @difficulty.map{|d| d }, class:"form-field" %>
  </div>
  <div class="field testing">
    <%= form.label :muscle_groups_used %>
    <%= form.select :muscle_groups, @muscle_groups.map{|m| m } %>
  </div>
  <div class="field">    
    <%= form.label :workout_type %>
    <%= form.select :workout_type, @workout_categories.map{|c| c } %>
  </div>    
  <div class="form-actions ">
  <button type="button" class="btn btn-primary btn-lg"><input type="submit" name="commit" value="Create Workout" class="btn create-btn" data-disable-with="Create Workout info"><%#= form.button :submit %></button>
  <button type="button" class="btn btn-primary btn-lg"><%= link_to 'Back', workout_infos_path %></button>
  </div>
<% end %>
</div>

app/views/workout_infos/edit.html.erb
<h1>Editing Workout Info</h1>

<%= render 'form', workout_info: @workout_info %>

<%= link_to 'Show', @workout_info %> |
<%= link_to 'Back', workout_infos_path %>

app/views/workout_infos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Your Workouts</h1>

<button type="button" class="home-btns"><%= link_to 'Create new workout', new_workout_info_path %></button>

<div class="card-rows">
    <% @workout_infos.map do |workout| %>
      <div class="card" style="width: 18rem;">
        <p><%#= image_tag(workout.picture, class:"card-img-top") if workout.picture.attached? %></p>
      
      <div class="card-body">
        <h5 class="card-title"><%= workout.name %></h5>
      </div>

      <ul class="list-group list-group-flush">
        <li class="list-group-item">Difficulty: <%= workout.difficulty%></li>
        <li class="list-group-item">Muscle groups: <%= workout.muscle_groups%></li>
        <li class="list-group-item">Workout Type: <%= workout.workout_type%></li>
      </ul>

      <div class="card-body">
        <%= link_to 'Show', workout %>
        <%= link_to 'Edit', edit_exercise_gallery_path(workout) %>
        <%= link_to 'Destroy', workout, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    </div>
    <% end %>
</div>

app/views/workout_infos/new.html.erb
<h1>New Workout</h1>

<%= render 'form', workout_info: @workout_info %>

app/views/workout_infos/show.html.erb
<p id="notice"><%= notice %></p>
<div class="heading-centered">
  <h1><%= @workout_info.name %></h1>
</div>
<div class="container show-workouts-table">
  <div class="show-workouts-row">
    <h3 class="table-headings">Difficulty</h3>
    <%= @workout_info.difficulty %>
  </div>
  <div class="show-workouts-row">
    <h3 class="table-headings">Muscle group/s</h3>
    <%= @workout_info.muscle_groups %>  
  </div>
  <div class="show-workouts-row">
    <h3 class="table-headings">Workout type</h3>
    <%= @workout_info.workout_type %>
  </div>
</div>

<div>
  
</div>

<div class="buttons">
  <button type="button" class="btn btn-primary btn-lg"><%= link_to "add exercises", new_exercise_info_path, class:"add-exercise" %></button>
  <button type="button" class="btn btn-secondary btn-lg"><%= link_to 'Edit', edit_workout_info_path(@workout_info) %></button>
  <button type="button" class="btn btn-secondary btn-lg"><%= link_to 'Back', workout_infos_path %></button>
</div>

<div>

</div>


 